### ISSUE TITLE
この実装に関して。

### ISSUE THREAD

**Issue by haniokasai** [NewDelion/Flowy#1]
https://github.com/NewDelion/Flowy/blob/master/Flowy/Flowy.php#L21

このようにしてしまうと、PHP7.2ではエラーを返すのですが、
this->start 時に代入してあげる形にしてあげてもかまわないのでしょうか。

**Comment by NewDelion** [comment]
あー、やっぱりphpでは宣言時のインスタンス代入はできないか…
修正しておきます。
ありがとうです。
